FROM alpine
MAINTAINER Joachim Westphal "elindorath@gmail.com"

# ENV NODE_VERSION=v4.2.6 NPM_VERSION=3

# RUN apk add --update \
#     curl \
#   && apk del \
#     curl \
#   && rm -rf \
#     /etc/ssl \
#     /var/cache/apk/*


CMD ["/bin/sh"]
